In [5]:
import os
import tensorflow as tf
import numpy as np

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.16425547, -0.5388796 ,  1.097508  ,  0.57160795,  0.15996355,
        -0.22083399, -0.8718391 ,  0.5253172 ,  0.44956428,  0.2986732 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.0642826 , 0.04419735, 0.22702324, 0.134176  , 0.08889963,
        0.06074656, 0.03168063, 0.12810646, 0.11876049, 0.10212705]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.801045

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 787us/step - loss: 0.2965 - accuracy: 0.91420s - los
Epoch 2/5
1875/1875 [==============================] - 1s 730us/step - loss: 0.1464 - accuracy: 0.9559
Epoch 3/5
1875/1875 [==============================] - 1s 770us/step - loss: 0.1104 - accuracy: 0.9657
Epoch 4/5
1875/1875 [==============================] - 2s 810us/step - loss: 0.0915 - accuracy: 0.9718
Epoch 5/5
1875/1875 [==============================] - 1s 781us/step - loss: 0.0760 - accuracy: 0.9765


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0788 - accuracy: 0.9752


[0.07880494743585587, 0.9751999974250793]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.2097117e-08, 4.9803530e-09, 2.4089859e-06, 4.7334343e-05,
        2.7796459e-12, 2.3287949e-07, 1.5323800e-13, 9.9994886e-01,
        7.2652234e-08, 1.1142198e-06],
       [7.2622319e-10, 5.2867032e-04, 9.9947137e-01, 5.5249153e-08,
        1.3753856e-16, 4.5012182e-08, 2.7838396e-09, 1.7048920e-12,
        3.6999712e-10, 2.9100523e-13],
       [4.1745643e-08, 9.9803537e-01, 1.6111550e-04, 3.7645236e-06,
        3.4296536e-05, 4.1594203e-06, 8.3621262e-07, 1.7139033e-03,
        4.3576489e-05, 3.0070814e-06],
       [9.9972230e-01, 2.6972697e-07, 8.4246887e-05, 7.7125442e-06,
        4.3324148e-06, 9.3747869e-05, 4.3500186e-06, 7.3200827e-05,
        9.1486896e-07, 8.8353372e-06],
       [6.7871711e-06, 2.2851095e-10, 5.6885356e-06, 2.0113106e-08,
        9.9669349e-01, 6.0258469e-07, 1.0741578e-06, 4.1955416e-05,
        2.1283522e-06, 3.2482482e-03]], dtype=float32)>